### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by queelyte** [explosivo22/kwikset-ha#32]
I have installed the github file via HACS and it shows in HACS as an installed integration. Iowever when I go to the + in under my main settings integrations tab, "kwikset" does not show as an available option.  How can I fix this?  If it requires a manual configuration, please tell me the steps to do it that way.

FYI-I see the Kwikset folder under my yaml custom_components folder.  Should I input information on that json file?  If so what?

Thanks in advance for your help!

**Comment by explosivo22** [comment]
@queelyte I will send you setup steps as soon as I get in front of my PC.

**Comment by queelyte** [comment]
Thanks! I really appreciate your help with this.

**Comment by explosivo22** [comment]
When you added the integration through HACS, you went to the custom repositories and add it that way?

**Comment by queelyte** [comment]
Yes, I did.

**Comment by queelyte** [comment]
I just did the core update, now I see the option in the UI. I should be set.

**Comment by explosivo22** [comment]
Awesome. I am going to go ahead and close this ticket since the main issue is solved. If you need help, please feel free to comment back on this ticket and we will get it all going.
