### ISSUE TITLE
Lock Battery Unit of Measurement

### ISSUE THREAD

**Issue by Jurykov** [explosivo22/kwikset-ha#33]
I added a lock through your integration.  I have a history graph on my dashboard showing battery levels of many of my devices.  When I tried to add the quickset battery level to my graph, but it doesn't seem to have a unit of measurement.  Because of this, it shows up as a horizontal bar graph instead of another trend line on my existing graph.  Any way to set the unit of measurement for the power level on these devices to '%'?

**Comment by explosivo22** [comment]
I will check this out. I probably missed setting it when I added.
