### ISSUE TITLE
Password Change on Kwikset Account

### ISSUE THREAD

**Issue by GlennPT** [explosivo22/kwikset-ha#46]
Been using kwikset-ha the integration for a while works great. I had to change the password on my Kwikset account, so now the integration won't connect. Is there a way to change the password for the integration in Home Assistant or do I have to remove and reinstall the integration. Thanks

Glenn Thibeault

**Comment by explosivo22** [comment]
Currently the integration does not support a password change.  I will look into this, but for now you should be able to remove and add back with nothing affected I believe as I have done this a couple of times.
