### ISSUE TITLE
How do you remove a device

### ISSUE THREAD

**Issue by rcork** [explosivo22/kwikset-ha#49]
How do you remove a device you no longer have? I had one of my Halos replaced under warranty and swapped in the new one but can't find a way in the UI to delete the old device.

**Comment by rcork** [comment]
I tried editing core.config_entries and core.device_registry but i screwed it up. I just ended up deleting the kwikset integration and then setting it up again from scratch. It would be great to have the ability to just delete an individual device instead of having to delete the integration.

**Comment by explosivo22** [comment]
I will check more into this for you
