### ISSUE TITLE
Warning from Home Assistant 

### ISSUE THREAD

**Issue by malmaxx** [explosivo22/kwikset-ha#50]
I saw this warning logged and wanted to pass along. 

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: February 6, 2023 at 9:57:16 PM (1 occurrences)
Last logged: February 6, 2023 at 9:57:16 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for kwikset using this method at custom_components/kwikset/__init__.py, line 53: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by explosivo22** [comment]
Thank you. I missed this one. I will get a fix out for this.
