### ISSUE TITLE
Refresh Token has been revoked - Started receiving this error in my HA logs today. 

### ISSUE THREAD

**Issue by bh56** [explosivo22/kwikset-ha#56]
Refresh Token has been revoked - Started receiving this error in my HA logs today.  Nothing has changed with my credentials.  Don't see where I can re-authenticate with the integration  Is something that changed on the Kwikset side?
Appreciate any insight about how to get this integration working again.    It has really been working great so far.  Thanks for the great work on this!

Logger: homeassistant.config_entries
Source: custom_components/kwikset/__init__.py:37
Integration: Kwikset Smart Locks ([documentation](https://github.com/explosivo22/kwikset-ha/))
First occurred: 12:36:18 PM (5 occurrences)
Last logged: 1:21:31 PM

Error setting up entry Adelwood for kwikset
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kwikset/__init__.py", line 37, in async_setup_entry
    await client.renew_access_token()
  File "/usr/local/lib/python3.10/site-packages/aiokwikset/api.py", line 189, in renew_access_token
    refresh_response = await client.initiate_auth(
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/client.py", line 225, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotAuthorizedException: An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Refresh Token has been revoked

**Comment by explosivo22** [comment]
I don't think anything has changed on the API side. I can still fully use it. I don't currently have reauthentication other than removing and adding back, but I have looked into it. I will see what I can get done.

**Comment by bh56** [comment]
> I don't think anything has changed on the API side. I can still fully use it. I don't currently have reauthentication other than removing and adding back, but I have looked into it. I will see what I can get done.

Thanks for the response.  Good to know it's still working for you.  Also, should this type of error also show up in notifications section?  I only saw that there was an issue in the integrations section.  I will take a snapshot and also see if remove and re-add will fix my current issues.   Unless you want me to sit tight and test out what you are thinking you might do?

**Comment by mingaldrichgan** [comment]
That happened to me at some point and yes, re-adding (and thus repeating
the authentication process) fixed it.

**Comment by bh56** [comment]
Ok, that worked.  Kept all my settings as well.  I'm good again for now.  Thanks for the further insight on this.

**Comment by explosivo22** [comment]
Glad to hear it is working and that everything stayed. I thought it would, but I hadn't checked in a while. I will go ahead and close this issue and we can track on #46 as I forgot earlier that I have an issue about this very thing already.
