### ISSUE TITLE
Potential enhancement request

### ISSUE THREAD

**Issue by bh56** [explosivo22/kwikset-ha#57]
Wanted to bounce this off the developer.  BTW, thanks again for creating this.  Like to control my devices with HA.  I've had a few times where it must be the auth token expires and I have to remove and re-add the integration.  Not a huge deal, as it seems to keep my configurations.  But wondering if there is a way to alert me if the integration is not working.   I'll dig more on the HA side.  Wasn't sure if you can put this in the integration.  I usually find out if something is wrong if my automations don't work or I happen to go into the integration page and see the error.   Appreciate any insight anyone can offer.

**Comment by explosivo22** [comment]
I will look into this. I am hoping to be able to put more time into this here soon as I have not been able to like I previously had.

**Comment by bh56** [comment]
That would be great.  I'm a solutions architect/tech enthusiast.  I started looking at your code and HA details.  LMK if you want help testing things out or anything else.  Thanks again!

**Comment by explosivo22** [comment]
I believe this to be something from HA itself. I have been unable to figure out a way to do it in my integration
