### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by renatkh** [explosivo22/kwikset-ha#61]
I encountered an error while trying to set up the Kwikset Smart Locks integration in Home Assistant. The error seems to originate from the async_setup_entry function in the __init__.py file of the custom integration.
Logs:
```
Logger: homeassistant.config_entries
Source: custom_components/kwikset/__init__.py:53
Integration: Kwikset Smart Locks (documentation)
First occurred: 11:48:15 PM (2 occurrences)
Last logged: 11:48:29 PM

Error setting up entry Home for kwikset
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kwikset/__init__.py", line 53, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```
## Additional Information:
Home Assistant 2023.7.2
Frontend 20230705.1

**Comment by drac0linux** [comment]
I tried to re-authenticate the addon with my Kwikset account and it worked tonight! Not sure what changed, but there have been a couple of minor home assistant updates since I tried last.

**Comment by bh56** [comment]
I got the Reconfigure message showing up for the Kwikset integration.  I clicked through and re-authenticated and it initially added the integration.  But then after a minute or two, goes to the "Failed to setup" message.  Appears something must have changed on the Kwikset API side of things?

**Comment by drac0linux** [comment]
Deleting the integration and re-adding it seems to fix it most of the time, except when it doesn't.

I don't know how it all works to know what is different when trying to reconfigure the integration, vs. removing it, re-adding it, and reconfiguring it. A cached file that doesn't update, perhaps?
