### ISSUE TITLE
Kwikset not found in Settings - Integrations -> Add Intergration

### ISSUE THREAD

**Issue by fslongo** [explosivo22/kwikset-ha#66]
Followed steps to add the custom integration through HACS
1. Go to integrations in HACS
2. click the 3 dots in the top right corner and choose custom repositories
3. paste the following into the repository input field https://github.com/explosivo22/kwikset-ha and choose category of Integration

Added in and restarted HA.  When going to settings - integrations - Add Integrations nothing shows up in the search for Kwikset Smart Locks.  

Any idea what I have done wrong?

Followed points under a closed discussion:
Repository added to HACS 
Hit F12 and then Cleared Cache and Hard Reload of HA
Still can't find Kwikset Integration

**Comment by fslongo** [comment]
Went through HACS again and loaded Kwikset from the Explore and Download repositories.  Works now.

**Comment by explosivo22** [comment]
Glad to hear you it working.
