### ISSUE TITLE
Requiring constant "reconfigure" processes

### ISSUE THREAD

**Issue by TopoTop1** [explosivo22/kwikset-ha#68]
Been working ok but as of 2 days ago it keeps coming up as Reconfigure Required. It makes me login with my kwikset account and get a code.

Using HAOS 2023.11.3

**Comment by TopoTop1** [comment]
Me too.

**Comment by TopoTop1** [comment]
Thank you so much @explosivo22 for looking at this for us!!! I appreciate your help!

**Comment by explosivo22** [comment]
tracking on #69 now. closing this one
