### ISSUE TITLE
Refresh Token Revoked

### ISSUE THREAD

**Issue by dingyifei** [explosivo22/kwikset-ha#69]
I'm having issues with receiving the verification code. It says refresh_token_revoked after I enter my account and password

**Comment by TopoTop1** [comment]
I am too. You may want to close this and add your issue to the ones that are already open?

**Comment by dingyifei** [comment]
I read the other issues, which seem related to re-logging in after adding. I can't add Kwikset integration because of this error tho.

**Comment by TopoTop1** [comment]
Mine won't even allow me to refresh the token. It just says Failed to Setup.

**Comment by dingyifei** [comment]
#68 and this issue seems to be related

**Comment by TopoTop1** [comment]
Probably

**Comment by TopoTop1** [comment]
@explosivo22 hi there.  

Any updates?

**Comment by johnbiddix** [comment]
I'm getting this error as well. I see the following after entering username and password

![image](https://github.com/explosivo22/kwikset-ha/assets/66189168/02b1888f-4082-4e29-9958-c5d4734d47c9)

**Comment by explosivo22** [comment]
Sorry for the delayed response.  This one has been unusually difficult to track down as I am unable to replicate this on my end no matter what I do, but also as there is not built in way to actually handle this error.  I am working on it though.

**Comment by explosivo22** [comment]
I have released an alpha to test something, but I am going to continue to try and trace this down.

**Comment by JBB2068** [comment]
> Sorry for the delayed response. This one has been unusually difficult to track down as I am unable to replicate this on my end no matter what I do, but also as there is not built in way to actually handle this error. I am working on it though.
> 
> Just for clarification, you all can get through the setup the initial time, but when it says you must reauthenticate is when it is failing?

Thank you for working on this! I am setting it up for the first time today and I get the message "refresh_token_revoked" when it asks for the verification code.

**Comment by explosivo22** [comment]
> > Sorry for the delayed response. This one has been unusually difficult to track down as I am unable to replicate this on my end no matter what I do, but also as there is not built in way to actually handle this error. I am working on it though.
> > Just for clarification, you all can get through the setup the initial time, but when it says you must reauthenticate is when it is failing?
> 
> Thank you for working on this! I am setting it up for the first time today and I get the message "refresh_token_revoked" when it asks for the verification code.

Are you using the the prerelease build, 0.2.4-alpha1, or the last official 0.2.3?

**Comment by dingyifei** [comment]
> > > Sorry for the delayed response. This one has been unusually difficult to track down as I am unable to replicate this on my end no matter what I do, but also as there is not built in way to actually handle this error. I am working on it though.
> 
> > > Just for clarification, you all can get through the setup the initial time, but when it says you must reauthenticate is when it is failing?
> 
> > 
> 
> > Thank you for working on this! I am setting it up for the first time today and I get the message "refresh_token_revoked" when it asks for the verification code.
> 
> 
> 
> Are you using the the prerelease build, 0.2.4-alpha1, or the last official 0.2.3?

I'm also trying to do the initial setup. The 0.2.4 alpha 1 shows unknown error occurred instead ![image](https://github.com/explosivo22/kwikset-ha/assets/15083013/293fb23b-eed6-4705-b635-4ca57be8427a)

**Comment by JBB2068** [comment]
> > > Sorry for the delayed response. This one has been unusually difficult to track down as I am unable to replicate this on my end no matter what I do, but also as there is not built in way to actually handle this error. I am working on it though.
> > > Just for clarification, you all can get through the setup the initial time, but when it says you must reauthenticate is when it is failing?
> > 
> > 
> > Thank you for working on this! I am setting it up for the first time today and I get the message "refresh_token_revoked" when it asks for the verification code.
> 
> Are you using the the prerelease build, 0.2.4-alpha1, or the last official 0.2.3?

Using last official 0.2.3

**Comment by StonyManager** [comment]
I have same problem and would be more than happy to try your 0.2.4 alpha release, but I don't know how to get it installed.

**Comment by StonyManager** [comment]
> I have same problem and would be more than happy to try your 0.2.4 alpha release, but I don't know how to get it installed.

I think I got the 0.2.4 alpha release installed. What information do you want? As expected, I still get the refresh token rejected error.

**Comment by TopoTop1** [comment]
Please don't close this as this is still active and a issue

**Comment by rXtwo** [comment]
Initial setup using official 0.2.3 resulted in “ refresh_token_revoked” - I attempted many times, but no change. Then I reset and downloaded alpha 0.2.4 which results in “unknown error occurred”

**Comment by ctracy** [comment]
I am trying this add-on for the very first time, using 0.2.4-alpha1.  I am having similar problems, I can extract more debug logs if you are interested. This is what happens: When I go to configure the integration (clicking "+ Add Integration", search for Kwikset locks), it pops up the email/password dialog, then I get the "How would you like to receive your verification code?". I have tried it both ways, I never seem to receive the verification code.  I see there are LOGGER.debug() calls in the code when it start to talk to the kwikset API, so I may try to enable that and see what I get.

**Comment by ctracy** [comment]
Here is where I am at with this... I found the python package aiokwikset which I believe to be maintained by the same author?  In any case, const.py shows a hostname ynk95r1v52.execute-api.us-east-1.amazonaws.com which I believe it would be communicating with, this hostname resolves to 4 IP addresses, 13.227.74.84 13.227.74.126 13.227.74.14 and 13.227.74.62. When running through the setup process for kwikset-ha and running a tcpdump on my router, I didn't see any packets to/from this IP address.  I did get the following backtrace from what appears to be the http request, I am not sure what to make of it:


===
2024-04-29 22:04:03.573 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 356, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 402, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kwikset/config_flow.py", line 189, in async_step_code
    await self.api.verify_user(self.pre_auth, user_input[CONF_CODE])
  File "/usr/local/lib/python3.12/site-packages/aiokwikset/api.py", line 278, in verify_user
    Session=pre_verification['Session'],
            ~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
===

**Comment by jaysenior** [comment]
Just installed this add-on myself and getting the same refresh_token_revoked with 2.3
