### ISSUE TITLE
Deprecated lock state on HA Core 2024.10

### ISSUE THREAD

**Issue by thayerfox** [explosivo22/kwikset-ha#75]
STATE_LOCKED was used from kwikset, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'kwikset' custom integration

**Comment by explosivo22** [comment]
I will be reviewing all of this and pulling it into once I get the backend API reworked. I plan on pushing it out with that update.

**Comment by explosivo22** [comment]
Fixed with pull request in 0.3.0. #76
