### ISSUE TITLE
Integration set up verification code error

### ISSUE THREAD

**Issue by scottsz100** [explosivo22/kwikset-ha#77]
When adding integration question comes up "How would you like to receive your verification code?" No matter what I chose, "Unkown error occurred" message comes up and can't get to next screen.
![image](https://github.com/user-attachments/assets/f190daeb-c515-4f3d-8c60-3c04a1c263f6)

**Comment by dipen26** [comment]
I am having same issue. Even tried after turning off 2FA, but nothing works. Can someone please help to resolve this issue? Thank you

**Comment by explosivo22** [comment]
I am looking into this.

**Comment by Guruleenyc** [comment]
Same issue here as well. Any resolution?

**Comment by Guruleenyc** [comment]
Seems to be resolve now. Thank you!

**Comment by dipen26** [comment]
Still same issue for me.

**Comment by scottsz100** [comment]
Still not resolved for me.

**Comment by scottsz100** [comment]
I updated HA core and now it works

**Comment by dipen26** [comment]
I did updated, and still getting the same error.

**Comment by explosivo22** [comment]
Just wanted to give everyone an update. I am currently working on a rewrite for the backend that we are using to try and get this fixed and the blocking call error fixed. I have made good progress and hope to have a test out soon that can be tried.

**Comment by explosivo22** [comment]
> I realize this comment may not be applicable to all, but wanted to share my experience.  I originally setup my Home Assistant on a VM using the Python Virtual Environment installation method.  It worked great for years, but I started to have issues with most of my HACS related integrations, including this one, and updating became a chore.  I switched to a docker based installation and continued to have issues with integrations and automations.  I rebuilt my HA on a new VM using HAOS about a year ago and have not had a single issue with any HACS integration since.  This Kwikset-ha integration has been rock solid for me since that change.  With many ways to install HA and their different versions, I am curious as to which installation methods are in use by those who are having issues?  Maybe it was just luck of a fresh and clean install or maybe there is something to be said for using the HAOS version?  

I have been running mine in a VM with HAOS and mine has been solid. I haven't once needed to reauthenticate.
